"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { AppRouterCacheProvider } from "@mui/material-nextjs/v14-appRouter";
import { ThemeProvider } from "@mui/material/styles";
import { theme } from "./theme/theme";
import { CssBaseline } from "@mui/material";
import Header from "./components/layout/hearder";
import RegisterModal from "./components/shared/registerModal";
import store from "./store/store";
import { Provider } from "react-redux";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <AppRouterCacheProvider>
          
            <ThemeProvider theme={theme}>
              <CssBaseline />
              <Provider store={store}>
              <Header>{children}</Header>
              <RegisterModal />
              </Provider>
            </ThemeProvider>
          
        </AppRouterCacheProvider>
      </body>
    </html>
  );
}
